FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    cmake \
    gcc \
    libc6-dev \
    libcurl4-openssl-dev \
    libssh2-1 \
    make \
    pkg-config
